# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spi_utility_raster_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SPIUtilityDialogBase(object):
    def setupUi(self, SPIUtilityDialogBase):
        SPIUtilityDialogBase.setObjectName("SPIUtilityDialogBase")
        SPIUtilityDialogBase.resize(900, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SPIUtilityDialogBase.sizePolicy().hasHeightForWidth())
        SPIUtilityDialogBase.setSizePolicy(sizePolicy)
        SPIUtilityDialogBase.setMinimumSize(QtCore.QSize(900, 423))
        SPIUtilityDialogBase.setMaximumSize(QtCore.QSize(900, 423))
        self.tabWidget = QtWidgets.QTabWidget(SPIUtilityDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 521, 351))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 24))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 451, 31))
        self.lineEdit.setToolTip("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton1 = QtWidgets.QPushButton(self.tab)
        self.pushButton1.setGeometry(QtCore.QRect(470, 50, 31, 31))
        self.pushButton1.setToolTip("")
        self.pushButton1.setObjectName("pushButton1")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 130, 451, 31))
        self.lineEdit_2.setToolTip("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(470, 130, 31, 31))
        self.pushButton.setToolTip("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(112, 194, 113, 31))
        self.lineEdit_3.setToolTip("")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(266, 200, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(358, 194, 113, 31))
        self.lineEdit_4.setToolTip("")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 250, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 250, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setToolTip("")
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(20, 390, 481, 16))
        self.label_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_6.setObjectName("label_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 342, 75, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 40, 451, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 40, 31, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(20, 14, 181, 16))
        self.label_22.setObjectName("label_22")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 166, 131, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(112, 210, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(332, 210, 121, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(246, 216, 71, 20))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(22, 217, 81, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(401, 268, 101, 41))
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 106, 31, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 106, 451, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(20, 80, 181, 20))
        self.label_23.setObjectName("label_23")
        self.comboBox = QtWidgets.QLineEdit(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(153, 159, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(240, 165, 191, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QLineEdit(self.tab_3)
        self.comboBox_6.setGeometry(QtCore.QRect(420, 158, 81, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(11, 96, 491, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(30)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 274, 91, 41))
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 15, 321, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 15, 31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 287, 81, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setGeometry(QtCore.QRect(101, 280, 81, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_5.setGeometry(QtCore.QRect(289, 280, 81, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(198, 287, 81, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 54, 321, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 54, 31, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_5 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_5.setGeometry(QtCore.QRect(-24, -8, 971, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(87, 143, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"padding-left: auto;\n"
"padding-top: 10px;")
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(SPIUtilityDialogBase)
        self.textEdit.setGeometry(QtCore.QRect(540, 80, 351, 301))
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_10 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_10.setGeometry(QtCore.QRect(540, 60, 46, 16))
        self.label_10.setObjectName("label_10")
        self.progressBar = QtWidgets.QProgressBar(SPIUtilityDialogBase)
        self.progressBar.setGeometry(QtCore.QRect(540, 390, 351, 20))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(0, 255, 0);\n"
"    width: 10px;\n"
"    margin: 1px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label_15 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_15.setGeometry(QtCore.QRect(20, 440, 391, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_16.setGeometry(QtCore.QRect(20, 470, 391, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_17.setGeometry(QtCore.QRect(20, 500, 391, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_18.setGeometry(QtCore.QRect(20, 530, 391, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_19.setGeometry(QtCore.QRect(20, 560, 91, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(SPIUtilityDialogBase)
        self.label_20.setGeometry(QtCore.QRect(100, 560, 46, 13))
        self.label_20.setObjectName("label_20")

        self.retranslateUi(SPIUtilityDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SPIUtilityDialogBase)

    def retranslateUi(self, SPIUtilityDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SPIUtilityDialogBase.setWindowTitle(_translate("SPIUtilityDialogBase", "SPI Utility"))
        self.label.setText(_translate("SPIUtilityDialogBase", "Input Precipitation Data Directory :"))
        self.pushButton1.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_2.setText(_translate("SPIUtilityDialogBase", "Output Data Directory :"))
        self.pushButton.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_3.setText(_translate("SPIUtilityDialogBase", "Start Year :"))
        self.label_4.setText(_translate("SPIUtilityDialogBase", "End Year :"))
        self.pushButton_2.setText(_translate("SPIUtilityDialogBase", "Check Data"))
        self.pushButton_4.setText(_translate("SPIUtilityDialogBase", "Generate Monthly Composite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SPIUtilityDialogBase", "Data Preparation"))
        self.label_6.setToolTip(_translate("SPIUtilityDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Data Status</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Incomplete :</span> Input parameters are not set. Complete the Data Preparation step.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Complete :</span> Data Preparation is complete. The SPI can be generated now.</p></body></html>"))
        self.label_6.setText(_translate("SPIUtilityDialogBase", "Data Status : Incomplete"))
        self.pushButton_8.setText(_translate("SPIUtilityDialogBase", "PushButton"))
        self.pushButton_9.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_22.setText(_translate("SPIUtilityDialogBase", "Monthly composites folder :"))
        self.label_7.setText(_translate("SPIUtilityDialogBase", "Time Scale (months): "))
        self.comboBox_2.setItemText(0, _translate("SPIUtilityDialogBase", "January"))
        self.comboBox_2.setItemText(1, _translate("SPIUtilityDialogBase", "February"))
        self.comboBox_2.setItemText(2, _translate("SPIUtilityDialogBase", "March"))
        self.comboBox_2.setItemText(3, _translate("SPIUtilityDialogBase", "April"))
        self.comboBox_2.setItemText(4, _translate("SPIUtilityDialogBase", "May"))
        self.comboBox_2.setItemText(5, _translate("SPIUtilityDialogBase", "June"))
        self.comboBox_2.setItemText(6, _translate("SPIUtilityDialogBase", "July"))
        self.comboBox_2.setItemText(7, _translate("SPIUtilityDialogBase", "August"))
        self.comboBox_2.setItemText(8, _translate("SPIUtilityDialogBase", "September"))
        self.comboBox_2.setItemText(9, _translate("SPIUtilityDialogBase", "October"))
        self.comboBox_2.setItemText(10, _translate("SPIUtilityDialogBase", "November"))
        self.comboBox_2.setItemText(11, _translate("SPIUtilityDialogBase", "December"))
        self.comboBox_3.setItemText(0, _translate("SPIUtilityDialogBase", "January"))
        self.comboBox_3.setItemText(1, _translate("SPIUtilityDialogBase", "February"))
        self.comboBox_3.setItemText(2, _translate("SPIUtilityDialogBase", "March"))
        self.comboBox_3.setItemText(3, _translate("SPIUtilityDialogBase", "April"))
        self.comboBox_3.setItemText(4, _translate("SPIUtilityDialogBase", "May"))
        self.comboBox_3.setItemText(5, _translate("SPIUtilityDialogBase", "June"))
        self.comboBox_3.setItemText(6, _translate("SPIUtilityDialogBase", "July"))
        self.comboBox_3.setItemText(7, _translate("SPIUtilityDialogBase", "August"))
        self.comboBox_3.setItemText(8, _translate("SPIUtilityDialogBase", "September"))
        self.comboBox_3.setItemText(9, _translate("SPIUtilityDialogBase", "October"))
        self.comboBox_3.setItemText(10, _translate("SPIUtilityDialogBase", "November"))
        self.comboBox_3.setItemText(11, _translate("SPIUtilityDialogBase", "December"))
        self.label_12.setText(_translate("SPIUtilityDialogBase", "End Month : "))
        self.label_11.setText(_translate("SPIUtilityDialogBase", "Start Month : "))
        self.pushButton_3.setText(_translate("SPIUtilityDialogBase", "Generate SPI"))
        self.pushButton_10.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_23.setText(_translate("SPIUtilityDialogBase", "Output folder :"))
        self.comboBox.setToolTip(_translate("SPIUtilityDialogBase", "<html><head/><body><p>Timescale (months) should have an integer value.</p></body></html>"))
        self.comboBox.setText(_translate("SPIUtilityDialogBase", "1"))
        self.label_8.setText(_translate("SPIUtilityDialogBase", "Accumulation Period (months): "))
        self.comboBox_6.setToolTip(_translate("SPIUtilityDialogBase", "<html><head/><body><p>Accumulation Period (months) should have an integer value between <span style=\" font-weight:600; color:#ff0000;\">1-60</span>.</p></body></html>"))
        self.comboBox_6.setText(_translate("SPIUtilityDialogBase", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SPIUtilityDialogBase", "SPI Calculation"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("SPIUtilityDialogBase", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("SPIUtilityDialogBase", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("SPIUtilityDialogBase", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("SPIUtilityDialogBase", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("SPIUtilityDialogBase", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("SPIUtilityDialogBase", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("SPIUtilityDialogBase", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("SPIUtilityDialogBase", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("SPIUtilityDialogBase", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("SPIUtilityDialogBase", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("SPIUtilityDialogBase", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("SPIUtilityDialogBase", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("SPIUtilityDialogBase", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("SPIUtilityDialogBase", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("SPIUtilityDialogBase", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("SPIUtilityDialogBase", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("SPIUtilityDialogBase", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("SPIUtilityDialogBase", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("SPIUtilityDialogBase", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("SPIUtilityDialogBase", "20"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("SPIUtilityDialogBase", "21"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("SPIUtilityDialogBase", "22"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("SPIUtilityDialogBase", "23"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("SPIUtilityDialogBase", "24"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("SPIUtilityDialogBase", "25"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("SPIUtilityDialogBase", "26"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("SPIUtilityDialogBase", "27"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("SPIUtilityDialogBase", "28"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("SPIUtilityDialogBase", "30"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("SPIUtilityDialogBase", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SPIUtilityDialogBase", "Class Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SPIUtilityDialogBase", "Upper Limit"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SPIUtilityDialogBase", "Lower Limit"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Extreme_Wet"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("SPIUtilityDialogBase", "10"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("SPIUtilityDialogBase", "2"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Severe_Wet"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("SPIUtilityDialogBase", "1.9999"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("SPIUtilityDialogBase", "1.5"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Moderate_Wet"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("SPIUtilityDialogBase", "1.4999"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("SPIUtilityDialogBase", "1.0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Mild_Wet"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("SPIUtilityDialogBase", "0.9999"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("SPIUtilityDialogBase", "0.5"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Normal"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("SPIUtilityDialogBase", "0.4999"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("SPIUtilityDialogBase", "-0.4999"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Mild_Drought"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("SPIUtilityDialogBase", "-0.5"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("SPIUtilityDialogBase", "-0.9999"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Moderate_Drought"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("SPIUtilityDialogBase", "-1"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("SPIUtilityDialogBase", "-1.4999"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Severe_Drought"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("SPIUtilityDialogBase", "-1.5"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("SPIUtilityDialogBase", "-1.9999"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("SPIUtilityDialogBase", "Extreme_Drought"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("SPIUtilityDialogBase", "-2"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("SPIUtilityDialogBase", "-10"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("SPIUtilityDialogBase", "Folder of SPI Values :"))
        self.pushButton_5.setText(_translate("SPIUtilityDialogBase", "Classify"))
        self.pushButton_6.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_13.setText(_translate("SPIUtilityDialogBase", "Start year :"))
        self.label_14.setText(_translate("SPIUtilityDialogBase", "End year :"))
        self.pushButton_7.setText(_translate("SPIUtilityDialogBase", "..."))
        self.label_21.setText(_translate("SPIUtilityDialogBase", "Output folder :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SPIUtilityDialogBase", "Analysis"))
        self.label_5.setText(_translate("SPIUtilityDialogBase", "Standardized Precipitation Index Utility (Raster Mode)"))
        self.textEdit.setToolTip(_translate("SPIUtilityDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEdit.setHtml(_translate("SPIUtilityDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Start with setting Input Precipitation Data Directory, Output Directory, Start Year and End Year. Then click on </span><span style=\" font-size:8pt; font-weight:600;\">Check Data</span><span style=\" font-size:8pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Note </span><span style=\" font-size:8pt;\">: The input precipitation data must satisfy the following conditions:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">1. The Annual Precipitation data should be in</span><span style=\" font-size:8pt; font-weight:600;\"> *.tif</span><span style=\" font-size:8pt;\"> format with daily rainfall data as its bands.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2. The precipitation rasters </span><span style=\" font-size:8pt; font-weight:600;\">must be georeferenced</span><span style=\" font-size:8pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">3. The dimensions (Rows and Columns) must be same for all the precipitation rasters.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Note </span><span style=\" font-size:8pt;\">: It is recommended that the output folder path should not have any subfolders and files.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#5500ff;\">For more information, refer the </span><a href=\"../Documentation.html\"><span style=\" font-size:8pt; text-decoration: underline; color:#5500ff;\">Documentation</span></a><span style=\" font-size:8pt; color:#5500ff;\">.</span></p>\n"
"<hr /></body></html>"))
        self.label_10.setText(_translate("SPIUtilityDialogBase", "Log :"))
        self.label_15.setText(_translate("SPIUtilityDialogBase", "TextLabel"))
        self.label_16.setText(_translate("SPIUtilityDialogBase", "TextLabel"))
        self.label_17.setText(_translate("SPIUtilityDialogBase", "0"))
        self.label_18.setText(_translate("SPIUtilityDialogBase", "0"))
        self.label_19.setText(_translate("SPIUtilityDialogBase", "No of Analysis"))
        self.label_20.setText(_translate("SPIUtilityDialogBase", "0"))
